"""add patients

Revision ID: 35687fa0b193
Revises: ac39a689b5fd
Create Date: 2026-09-26 18:07:52.283942
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '35687fa0b193'
down_revision: str | None = 'ac39a689b5fd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('medical_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'completed', 'on_hold', name='patient_status'), nullable=False),
    sa.Column('assigned_therapist_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_therapist_id'], ['therapists.id'], name=op.f('fk_patients_assigned_therapist_id_therapists'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patients'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patients')
    # ### end Alembic commands ###
