"""add appointments

Revision ID: 46583c12eeda
Revises: 35687fa0b193
Create Date: 2026-09-26 23:46:05.000462
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '46583c12eeda'
down_revision: str | None = '35687fa0b193'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('therapist_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'completed', name='appointment_status'), nullable=False),
    sa.Column('payment_method', sa.Enum('cash', 'card', 'insurance', name='payment_method'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_appointments_patient_id_patients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['therapist_id'], ['therapists.id'], name=op.f('fk_appointments_therapist_id_therapists')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointments')),
    sa.UniqueConstraint('therapist_id', 'date', 'start_time', name='uq_appointments_therapist_id_date_start_time')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table('appointments')
    # create_table implicitly created these enum types; drop them so re-upgrade succeeds.
    sa.Enum(name='appointment_status').drop(op.get_bind())
    sa.Enum(name='payment_method').drop(op.get_bind())
