"""add therapists and schedule overrides

Revision ID: ac39a689b5fd
Revises: 0002
Create Date: 2026-09-25 16:54:07.253414
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ac39a689b5fd'
down_revision: str | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('therapists',
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('specialty', sa.String(length=120), nullable=False),
    sa.Column('working_days', postgresql.ARRAY(sa.SmallInteger()), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('slot_duration_minutes', sa.Integer(), server_default=sa.text('30'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_therapists'))
    )
    op.create_table('therapist_schedule_overrides',
    sa.Column('therapist_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_day_off', sa.Boolean(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['therapist_id'], ['therapists.id'], name=op.f('fk_therapist_schedule_overrides_therapist_id_therapists'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_therapist_schedule_overrides')),
    sa.UniqueConstraint('therapist_id', 'date', name='uq_therapist_schedule_overrides_therapist_id_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('therapist_schedule_overrides')
    op.drop_table('therapists')
    # ### end Alembic commands ###
